mutators:
  - cxx_add_to_sub
  - cxx_sub_to_add
  - cxx_mul_to_div
  - cxx_div_to_mul
  - cxx_eq_to_ne
  - cxx_ne_to_eq
  - cxx_gt_to_ge
  - cxx_ge_to_gt
  - cxx_lt_to_le
  - cxx_le_to_lt
  - cxx_logical_and_to_or
  - cxx_logical_or_to_and
excludePaths:
  - .*/subprojects/.*
  - .*/tests/.*
  - .*/build/.*
timeout: 10000
quiet: false
